### ISSUE TITLE
onBackgroundMessage not working

### ISSUE THREAD

**Issue by deepa1-d** [chemerisuk/cordova-plugin-firebase-messaging#128] opened 2020-03-02 08:31 UTC
onBackgroundMessage is not called when a notification is received on the app. onMessage is called when I click on the notification, but before that nothing in onBackgroundMessage.

**Comment by chemerisuk** [comment] 2020-04-23 08:55
Possible duplicate of https://github.com/chemerisuk/cordova-plugin-firebase-messaging/issues/95

**Closed by chemerisuk** 2020-04-23 08:55 UTC
